name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11.4
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app
    - name: Update fastlane
      run: |
        cd Emitron
        bundle install
        bundle exec fastlane -v
    - name: Download secrets
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        scripts/download_s3.sh development > Emitron/Emitron/Configuration/secrets.development.xcconfig
        scripts/download_s3.sh beta > Emitron/Emitron/Configuration/secrets.beta.xcconfig
        scripts/download_s3.sh production > Emitron/Emitron/Configuration/secrets.production.xcconfig
    - name: Execute fastlane
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 5
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 5
      run: |
        cd Emitron
        bundle exec fastlane -v
        bundle exec fastlane tests
